### ISSUE TITLE
No need for <inst_realm> for SPs

### ISSUE THREAD

**Issue by wbackman** [CESNET/eduroam-db#1]
converter.py should not require inst_realm when the organisation is an SP.

I think you need to change get_data to require inst_realm only if the organisation is IdP or IdP+SP.

Regards,

Wenche

**Comment by lager1** [comment]
Hi,

why do you think that `inst_realm` should not be required when the organization is an SP? SP organizations do not have their own users, so the only real users of eduroam are users from others organizations. This needs to work correctly in eduroam infrastructure and visited institution and user's realm are core elements of this.

The fix in the code for this is quite simple:
```diff
git diff converter.py
diff --git a/converter/converter.py b/converter/converter.py
index 9ce5e47..c0ea213 100755
--- a/converter/converter.py
+++ b/converter/converter.py
@@ -425,8 +425,9 @@ def get_data(root, filename, options):
   ret["stage"] = config.default_stage                     # stage, default value set to 1
 
   ret["inst_realm"] = []                                  # inst_realm
-  for i in root.institution.inst_realm:                   # iterate realm and add to ret
-    ret["inst_realm"].append(i)
+  if hasattr(root.institution, 'inst_realm'):
+    for i in root.institution.inst_realm:                   # iterate realm and add to ret
+      ret["inst_realm"].append(i)
 
   ret["inst_name"] = get_inst_name(root, required_lang)   # inst_name
```

As I've said i don't think this is totally correct to do. The produced json contains empty `inst_realm` array, which is the same problem as in xml.

**Comment by wbackman** [comment]
Hi, 

According to this document [ https://monitor.eduroam.org/eduroam-database/v2/docs/eduroam-database-ver17102017.pdf | https://monitor.eduroam.org/eduroam-database/v2/docs/eduroam-database-ver17102017.pdf ] inst_realm is only for IdP and IdP+SP, furthermore "for type SP no realms should be specified". 

Regards, 

Wenche

**Comment by lager1** [comment]
Hi,

you are right. While i respect the document you linked I do not think, that this is correct based on eduroam hierarchical structure. Every eduroam AP needs to be connected to some RADIUS server which has to identify itself somehow in the eduroam infrastructure.

My advice is to discuss this matter in some broader eduroam related community.

I've added the code that solves this issue. The code does not strictly follow the spec in the linked document - if there are any realms for SP type, they are added to JSON output. I feel that this i better than just discarding available data.

If this enough for you?

**Comment by JanOppolzer** [comment]
Nahrazeno novou aplikací pokryti.eduroam.cz.
