### ISSUE TITLE
Informační URL v Českém jazyce

### ISSUE THREAD

**Issue by semik** [CESNET/eduroam-db#3]
Prosim zmenit popisek 

Informační URL v Českém jazyce

na

Informační pro návštěvníky URL v Českém jazyce:

**Comment by lager1** [comment]
upraveno v https://github.com/CESNET/eduroam-db/commit/0ac1c6a779a1215f0a782b3da33e31fb10246b09

Chceme stejne upravit i popisky pro anglicke URL?

**Comment by semik** [comment]
> Chceme stejne upravit i popisky pro anglicke URL?

Jasne.

Diky

**Comment by lager1** [comment]
opraveno v https://github.com/CESNET/eduroam-db/commit/b48430b9400b816edc59b22d826e7ceef9b5bfc4
