### ISSUE TITLE
Špatně zobrazený autor poslední změny

### ISSUE THREAD

**Issue by semik** [CESNET/eduroam-db#4]
V případě že dojde ke změně parametrů organizace mimo klikací webové rozhraní tak aplikace správně zobrazuje datum poslední změny, už ale nikoliv autora. Např. v případě změny SP -> IdPSP u GUH.json:

> 
> root@monitor:/home/eduroamdb/eduroam-db/web/coverage/coverage_files# git log GUH.json 
> commit d895c3ecfdcb74158c181a801d58b2ae8b474ce1
> Author: info@eduroam.cz <info@eduroam.cz>
> Date:   Sun Oct 20 00:01:01 2019 +0200
> 
>     Automatická úprava dat z důvodu rozdílů v evidenci eduroam.cz
> 
> commit 6776eed30e8934f3a906d7761380e1feaabf89a1
> Author: Václav Mach <vaclav.mach@cesnet.cz>
> Date:   Tue Mar 12 14:02:48 2019 +0100
> 
>     Import dat

Zobrazuje "Datum poslední změny: 20. 10. 2019 0:01:00Autor: machv@cesnet.cz" i když autorem by měl být spíš "systém", nebo něco takového.

**Comment by JanOppolzer** [comment]
Nahrazeno novou aplikací pokryti.eduroam.cz.
